apiVersion: v1
kind: Service
metadata:
  name: sre-app-lb
  namespace: sre-project
spec:
  type: LoadBalancer
  selector:
    app: sre-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000